image: cpaulik/gitlab-ci-image:v2
before_script:
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

after_script:
  - conda env remove -n swi_env

variables:
  GIT_SSL_NO_VERIFY: "true"
  PIP_EXTRA_INDEX_URL: "http://dvlp1.geo.tuwien.ac.at:8080/simple"
  PIP_TRUSTED_HOST: "dvlp1.geo.tuwien.ac.at"
  PIP_USE_WHEEL: "yes"
  NO_PROXY: "dvlp1.geo.tuwien.ac.at,$NO_PROXY"
  no_proxy: "dvlp1.geo.tuwien.ac.at,$no_proxy"

stages:
- test
- release

test_py27:
  stage: test
  script:
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda create -q -n swi_env cython numpy pandas netCDF4 pyproj scipy
    - source activate swi_env
    - pip install pygeobase
    - pip install pygeogrids
    - pip install pykdtree
    - pip install pytesmo
    - pip install iterative_storage
    - python setup.py test
  except:
    - tags

test_py36:
  stage: test
  script:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda create -q -n swi_env cython numpy pandas netCDF4 pyproj scipy
    - source activate swi_env
    - pip install pygeobase
    - pip install pygeogrids
    - pip install pykdtree
    - pip install pytesmo
    - pip install iterative_storage
    - python setup.py test
  except:
    - tags

release_job:
  stage: release
  script:
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda create -q -n swi_env cython numpy pandas netCDF4 pyproj scipy
    - source activate swi_env
    - pip install pygeobase
    - pip install pygeogrids
    - pip install pykdtree
    - pip install pytesmo
    - pip install iterative_storage
    - python setup.py test
    - python setup.py sdist
  artifacts:
    paths:
      - dist/*.tar.gz
  only:
    - tags
