name: pyswi
dependencies:
- cython
- numpy<2
- pandas
- netCDF4
- pyproj
- scipy
- pip
- pip:
  - cadati
  - pygeobase
  - pygeogrids
  - pykdtree
  - pyparsing
  - trollsift
  - pytest
  - pytest-cov
