name: swi_env
dependencies:
- cython=0.25.2=py27_0
- mkl=2017.0.1=0
- numpy=1.12.0=py27_0
- openssl=1.0.2k=1
- pandas=0.19.2=np112py27_1
- pip=9.0.1=py27_1
- py=1.4.32=py27_0
- pytest=3.0.6=py27_0
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2016.10=py27_0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - cycler==0.10.0
  - functools32==3.2.3.post2
  - matplotlib==2.0.0
  - netcdf4==1.2.7
  - pygeobase==0.3.11
  - pygeogrids==0.2.2
  - pykdtree==1.2.1
  - pyparsing==2.2.0
  - pyproj==1.9.5.1
  - pytesmo==0.6.2
  - scipy==0.18.1
  - subprocess32==3.2.7
  - iterative_storage==0.1

